### ISSUE TITLE
enhancement - mouse wheel scroll

### ISSUE THREAD

**Issue by scrapeable** [AdrianAntico/AutoPlots#1]
I've forked this repo so planning to add this myself, but either way I think this would be a useful code chunk to add to any plots with a zoom.

https://github.com/JohnCoene/echarts4r/issues/588

**Comment by AdrianAntico** [comment]
@scrapeable thanks for bringing this up. I was unaware of this functionality. Do you think there should be a parameter the user sets to enable this or turn it off?

I just looked into this and I think I need to add this as a parameter option. Reason being is the auto scroll feature might not be desirable for the Quantico app since many plots can be stacked on top of each other and mouse scrolling is the primary way to achieve this. I'll name the parameter MouseScroll = FALSE as the default just to minimize efforts needed from the Quantico side of things.

**Comment by AdrianAntico** [comment]
@scrapeable one issue I just noticed is that if you create a faceted plot that only some of the plots are scrollable. For example, I just created a 2x2 facet density plot and when I scrolled the top left plot the top right plot zoomed when I believe we would want just the top left to zoom. Also, when I scrolled on the bottom plots neither of them zoomed upon scroll. Seems like the zoom property gets applied inconsistently with faceting. I can submit a ticket on echarts4r with this one. I'll enable it to operate with faceting for now but be aware it won't work until that gets resolved.

**Comment by scrapeable** [comment]
Honestly I would just have it as default, but maybe having a MouseScoll = TRUE /FALSE input would be good. I haven't tested it out but it might have weird functionality on a laptop touchpads. Either way this is small but I think it adds value.

**Comment by AdrianAntico** [comment]
@scrapeable the main motivation for the parameter is so I don't have to have it enabled for the Quantico app or if others wanted to create a similar type of app. Reason being is that with many plots being displayed in the app that all stack on top of each other, the scroll functionality can get annoying. Otherwise, I love the feature. I can have it default to TRUE so as to make life easier for users. It really won't be too much extra effort to disable it in the app.

**Comment by AdrianAntico** [comment]
@scrapeable I just pushed an update with the MouseScroll parameter added to relevant plots. Default is set to TRUE. Feel free to reinstall to have the updates. Thanks again for the great suggestion!
